version: '3.9'
services:
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    container_name: treview
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: treview
    networks:
      - esnet
    ports:
      - 5432:5432

networks:
  esnet:
